# Generated by Django 3.1.3 on 2021-04-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='phone',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
