# Generated by Django 3.1.3 on 2021-04-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20210404_1611'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
                ('sku', models.TextField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('srp_price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('image', models.TextField(null=True)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.suppliers')),
            ],
        ),
    ]
