# Generated by Django 3.1.3 on 2021-04-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
